capitalized messages

diff --git a/control-restore b/control-restore
--- a/control-restore
+++ b/control-restore
@@ -12,10 +12,10 @@ for FACILITY in "$@"; do
 		if [ -n "$STATUS" -a "$STATUS" != unknown ]; then
 			/usr/sbin/control "$FACILITY" "$STATUS"
 		else
-			echo "${0##*/}: status \"$STATUS\" for \"$FACILITY\" facility cannot be restored" >&2
+			echo "${0##*/}: Status \"$STATUS\" for \"$FACILITY\" facility cannot be restored" >&2
 		fi
 	else
-		echo "${0##*/}: no status available for \"$FACILITY\" facility" >&2
+		echo "${0##*/}: No status available for \"$FACILITY\" facility" >&2
 	fi
 	rm -f "$FILE"
 done
